service: slack-codepipeline-notifications

provider:
  name: aws
  runtime: nodejs12.x

  stage: production
  region: us-west-2

  environment:
      SLACK_WEBHOOK_URL: https://CHANGEME

functions:
  notification:
    handler: handler.run

    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.codepipeline"
            detail-type:
              - "CodePipeline Pipeline Execution State Change"
            detail:
              state:
                - STARTED
                - FAILED
                - IN_PROGRESS
                - CANCELED
                - SUCCEEDED
